version: "3.5"
services:
    jenkin:
        container_name: jenkins-muiru
        image: jenkins/jenkins
        ports:
            - 8083:8080
            - 5000:5000
        volumes:
            - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home:
